// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
//import AppleProductTypes

let package = Package(
    name: "FLEXIVE",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .library(
            name: "FLEXIVE",
            targets: ["AppModule"]
        )
    ],
    targets: [
        .target(
            name: "AppModule",
            path: "."
        )
    ]
)